import { getLang, type Lang } from '../i18n/strings';
import { toCyrillic } from '../i18n/extra/cyrillic';

/**
 * Tekstet e aktivizimit dhe të programit "të gjitha bashkë", në 31 gjuhët.
 * Janë më vete nga src/i18n që kodet të mos prekin përkthimet e programeve.
 */
const KEYS = ['title', 'intro', 'placeholder', 'activate', 'invalid', 'wrongProgram', 'expired', 'renew', 'badge', 'days', 'life', 'change', 'close', 'noCrypto', 'activated', 'allSub', 'allLibs'] as const;
export type LicenseKey = (typeof KEYS)[number];
type Texts = Record<LicenseKey, string>;

const sq: Texts = {
  title: 'Aktivizo programin',
  intro: 'Shkruaj kodin e aktivizimit që të ka dhënë administratori.',
  placeholder: 'Kodi i aktivizimit',
  activate: 'Aktivizo',
  invalid: 'Kodi nuk është i vlefshëm.',
  wrongProgram: 'Ky kod është për një program tjetër.',
  expired: 'Ky kod ka skaduar më {date}.',
  renew: 'Licenca ka skaduar. Kërko një kod të ri nga administratori.',
  badge: 'Licenca',
  days: '{n} ditë, deri më {date}',
  life: 'Përjetë',
  change: 'Ndrysho kodin',
  close: 'Mbyll',
  noCrypto: 'Ky shfletues nuk mund ta kontrollojë kodin. Hape programin me Chrome, Edge, Firefox ose Safari të përditësuar.',
  activated: 'Programi u aktivizua.',
  allSub: 'Të gjitha programet në një',
  allLibs: 'Të gjitha',
};

const en: Texts = {
  title: 'Activate the program',
  intro: 'Enter the activation code you received from the administrator.',
  placeholder: 'Activation code',
  activate: 'Activate',
  invalid: 'The code is not valid.',
  wrongProgram: 'This code is for another program.',
  expired: 'This code expired on {date}.',
  renew: 'The license has expired. Ask the administrator for a new code.',
  badge: 'License',
  days: '{n} days, until {date}',
  life: 'Lifetime',
  change: 'Change code',
  close: 'Close',
  noCrypto: 'This browser cannot check the code. Open the program in an up-to-date Chrome, Edge, Firefox or Safari.',
  activated: 'The program is activated.',
  allSub: 'All programs in one',
  allLibs: 'All',
};

const it: Texts = {
  title: 'Attiva il programma',
  intro: "Inserisci il codice di attivazione ricevuto dall'amministratore.",
  placeholder: 'Codice di attivazione',
  activate: 'Attiva',
  invalid: 'Il codice non è valido.',
  wrongProgram: 'Questo codice è per un altro programma.',
  expired: 'Questo codice è scaduto il {date}.',
  renew: "La licenza è scaduta. Chiedi un nuovo codice all'amministratore.",
  badge: 'Licenza',
  days: '{n} giorni, fino al {date}',
  life: 'A vita',
  change: 'Cambia codice',
  close: 'Chiudi',
  noCrypto: 'Questo browser non può verificare il codice. Apri il programma con Chrome, Edge, Firefox o Safari aggiornati.',
  activated: 'Il programma è attivato.',
  allSub: 'Tutti i programmi in uno',
  allLibs: 'Tutte',
};

const de: Texts = {
  title: 'Programm aktivieren',
  intro: 'Gib den Aktivierungscode ein, den du vom Administrator erhalten hast.',
  placeholder: 'Aktivierungscode',
  activate: 'Aktivieren',
  invalid: 'Der Code ist ungültig.',
  wrongProgram: 'Dieser Code gilt für ein anderes Programm.',
  expired: 'Dieser Code ist am {date} abgelaufen.',
  renew: 'Die Lizenz ist abgelaufen. Fordere beim Administrator einen neuen Code an.',
  badge: 'Lizenz',
  days: '{n} Tage, bis {date}',
  life: 'Unbegrenzt',
  change: 'Code ändern',
  close: 'Schließen',
  noCrypto: 'Dieser Browser kann den Code nicht prüfen. Öffne das Programm in einem aktuellen Chrome, Edge, Firefox oder Safari.',
  activated: 'Das Programm ist aktiviert.',
  allSub: 'Alle Programme in einem',
  allLibs: 'Alle',
};

const fr: Texts = {
  title: 'Activer le programme',
  intro: "Saisissez le code d'activation reçu de l'administrateur.",
  placeholder: "Code d'activation",
  activate: 'Activer',
  invalid: "Le code n'est pas valide.",
  wrongProgram: 'Ce code est pour un autre programme.',
  expired: 'Ce code a expiré le {date}.',
  renew: "La licence a expiré. Demandez un nouveau code à l'administrateur.",
  badge: 'Licence',
  days: "{n} jours, jusqu'au {date}",
  life: 'À vie',
  change: 'Changer le code',
  close: 'Fermer',
  noCrypto: 'Ce navigateur ne peut pas vérifier le code. Ouvrez le programme dans Chrome, Edge, Firefox ou Safari à jour.',
  activated: 'Le programme est activé.',
  allSub: 'Tous les programmes en un',
  allLibs: 'Toutes',
};

const es: Texts = {
  title: 'Activar el programa',
  intro: 'Introduce el código de activación que te dio el administrador.',
  placeholder: 'Código de activación',
  activate: 'Activar',
  invalid: 'El código no es válido.',
  wrongProgram: 'Este código es para otro programa.',
  expired: 'Este código caducó el {date}.',
  renew: 'La licencia ha caducado. Pide un código nuevo al administrador.',
  badge: 'Licencia',
  days: '{n} días, hasta el {date}',
  life: 'De por vida',
  change: 'Cambiar código',
  close: 'Cerrar',
  noCrypto: 'Este navegador no puede comprobar el código. Abre el programa en Chrome, Edge, Firefox o Safari actualizados.',
  activated: 'El programa está activado.',
  allSub: 'Todos los programas en uno',
  allLibs: 'Todas',
};

const pt: Texts = {
  title: 'Ativar o programa',
  intro: 'Introduza o código de ativação recebido do administrador.',
  placeholder: 'Código de ativação',
  activate: 'Ativar',
  invalid: 'O código não é válido.',
  wrongProgram: 'Este código é para outro programa.',
  expired: 'Este código expirou em {date}.',
  renew: 'A licença expirou. Peça um novo código ao administrador.',
  badge: 'Licença',
  days: '{n} dias, até {date}',
  life: 'Vitalícia',
  change: 'Alterar código',
  close: 'Fechar',
  noCrypto: 'Este navegador não consegue verificar o código. Abra o programa no Chrome, Edge, Firefox ou Safari atualizados.',
  activated: 'O programa está ativado.',
  allSub: 'Todos os programas num só',
  allLibs: 'Todas',
};

const nl: Texts = {
  title: 'Programma activeren',
  intro: 'Voer de activeringscode in die je van de beheerder hebt gekregen.',
  placeholder: 'Activeringscode',
  activate: 'Activeren',
  invalid: 'De code is niet geldig.',
  wrongProgram: 'Deze code is voor een ander programma.',
  expired: 'Deze code is verlopen op {date}.',
  renew: 'De licentie is verlopen. Vraag de beheerder om een nieuwe code.',
  badge: 'Licentie',
  days: '{n} dagen, tot {date}',
  life: 'Levenslang',
  change: 'Code wijzigen',
  close: 'Sluiten',
  noCrypto: 'Deze browser kan de code niet controleren. Open het programma in een actuele Chrome, Edge, Firefox of Safari.',
  activated: 'Het programma is geactiveerd.',
  allSub: 'Alle programma’s in één',
  allLibs: 'Alle',
};

const da: Texts = {
  title: 'Aktivér programmet',
  intro: 'Indtast aktiveringskoden, du har fået af administratoren.',
  placeholder: 'Aktiveringskode',
  activate: 'Aktivér',
  invalid: 'Koden er ikke gyldig.',
  wrongProgram: 'Denne kode er til et andet program.',
  expired: 'Denne kode udløb den {date}.',
  renew: 'Licensen er udløbet. Bed administratoren om en ny kode.',
  badge: 'Licens',
  days: '{n} dage, til {date}',
  life: 'Livstid',
  change: 'Skift kode',
  close: 'Luk',
  noCrypto: 'Denne browser kan ikke kontrollere koden. Åbn programmet i en opdateret Chrome, Edge, Firefox eller Safari.',
  activated: 'Programmet er aktiveret.',
  allSub: 'Alle programmer i ét',
  allLibs: 'Alle',
};

const sv: Texts = {
  title: 'Aktivera programmet',
  intro: 'Ange aktiveringskoden du fått av administratören.',
  placeholder: 'Aktiveringskod',
  activate: 'Aktivera',
  invalid: 'Koden är inte giltig.',
  wrongProgram: 'Den här koden gäller ett annat program.',
  expired: 'Den här koden gick ut den {date}.',
  renew: 'Licensen har gått ut. Be administratören om en ny kod.',
  badge: 'Licens',
  days: '{n} dagar, till {date}',
  life: 'Livstid',
  change: 'Byt kod',
  close: 'Stäng',
  noCrypto: 'Den här webbläsaren kan inte kontrollera koden. Öppna programmet i en uppdaterad Chrome, Edge, Firefox eller Safari.',
  activated: 'Programmet är aktiverat.',
  allSub: 'Alla program i ett',
  allLibs: 'Alla',
};

const fi: Texts = {
  title: 'Aktivoi ohjelma',
  intro: 'Kirjoita ylläpitäjältä saamasi aktivointikoodi.',
  placeholder: 'Aktivointikoodi',
  activate: 'Aktivoi',
  invalid: 'Koodi ei ole kelvollinen.',
  wrongProgram: 'Tämä koodi on toiselle ohjelmalle.',
  expired: 'Tämä koodi vanheni {date}.',
  renew: 'Lisenssi on vanhentunut. Pyydä ylläpitäjältä uusi koodi.',
  badge: 'Lisenssi',
  days: '{n} päivää, {date} asti',
  life: 'Pysyvä',
  change: 'Vaihda koodi',
  close: 'Sulje',
  noCrypto: 'Tämä selain ei voi tarkistaa koodia. Avaa ohjelma päivitetyllä Chromella, Edgellä, Firefoxilla tai Safarilla.',
  activated: 'Ohjelma on aktivoitu.',
  allSub: 'Kaikki ohjelmat yhdessä',
  allLibs: 'Kaikki',
};

const et: Texts = {
  title: 'Aktiveeri programm',
  intro: 'Sisesta administraatorilt saadud aktiveerimiskood.',
  placeholder: 'Aktiveerimiskood',
  activate: 'Aktiveeri',
  invalid: 'Kood ei ole kehtiv.',
  wrongProgram: 'See kood on teise programmi jaoks.',
  expired: 'See kood aegus {date}.',
  renew: 'Litsents on aegunud. Küsi administraatorilt uus kood.',
  badge: 'Litsents',
  days: '{n} päeva, kuni {date}',
  life: 'Eluaegne',
  change: 'Muuda koodi',
  close: 'Sulge',
  noCrypto: 'See brauser ei saa koodi kontrollida. Ava programm uuendatud Chrome’is, Edge’is, Firefoxis või Safaris.',
  activated: 'Programm on aktiveeritud.',
  allSub: 'Kõik programmid ühes',
  allLibs: 'Kõik',
};

const lv: Texts = {
  title: 'Aktivizēt programmu',
  intro: 'Ievadi aktivizācijas kodu, ko saņēmi no administratora.',
  placeholder: 'Aktivizācijas kods',
  activate: 'Aktivizēt',
  invalid: 'Kods nav derīgs.',
  wrongProgram: 'Šis kods ir citai programmai.',
  expired: 'Šī koda derīgums beidzās {date}.',
  renew: 'Licence ir beigusies. Palūdz administratoram jaunu kodu.',
  badge: 'Licence',
  days: '{n} dienas, līdz {date}',
  life: 'Mūža',
  change: 'Mainīt kodu',
  close: 'Aizvērt',
  noCrypto: 'Šī pārlūkprogramma nevar pārbaudīt kodu. Atver programmu atjauninātā Chrome, Edge, Firefox vai Safari.',
  activated: 'Programma ir aktivizēta.',
  allSub: 'Visas programmas vienā',
  allLibs: 'Visas',
};

const lt: Texts = {
  title: 'Aktyvuoti programą',
  intro: 'Įvesk aktyvavimo kodą, kurį gavai iš administratoriaus.',
  placeholder: 'Aktyvavimo kodas',
  activate: 'Aktyvuoti',
  invalid: 'Kodas negalioja.',
  wrongProgram: 'Šis kodas skirtas kitai programai.',
  expired: 'Šio kodo galiojimas baigėsi {date}.',
  renew: 'Licencija baigėsi. Paprašyk administratoriaus naujo kodo.',
  badge: 'Licencija',
  days: '{n} d., iki {date}',
  life: 'Neterminuota',
  change: 'Keisti kodą',
  close: 'Uždaryti',
  noCrypto: 'Ši naršyklė negali patikrinti kodo. Atidaryk programą atnaujintoje Chrome, Edge, Firefox arba Safari.',
  activated: 'Programa aktyvuota.',
  allSub: 'Visos programos vienoje',
  allLibs: 'Visos',
};

const pl: Texts = {
  title: 'Aktywuj program',
  intro: 'Wpisz kod aktywacyjny otrzymany od administratora.',
  placeholder: 'Kod aktywacyjny',
  activate: 'Aktywuj',
  invalid: 'Kod jest nieprawidłowy.',
  wrongProgram: 'Ten kod jest do innego programu.',
  expired: 'Ten kod wygasł {date}.',
  renew: 'Licencja wygasła. Poproś administratora o nowy kod.',
  badge: 'Licencja',
  days: '{n} dni, do {date}',
  life: 'Dożywotnia',
  change: 'Zmień kod',
  close: 'Zamknij',
  noCrypto: 'Ta przeglądarka nie może sprawdzić kodu. Otwórz program w aktualnym Chrome, Edge, Firefox lub Safari.',
  activated: 'Program jest aktywny.',
  allSub: 'Wszystkie programy w jednym',
  allLibs: 'Wszystkie',
};

const cs: Texts = {
  title: 'Aktivovat program',
  intro: 'Zadej aktivační kód, který jsi dostal od administrátora.',
  placeholder: 'Aktivační kód',
  activate: 'Aktivovat',
  invalid: 'Kód není platný.',
  wrongProgram: 'Tento kód je pro jiný program.',
  expired: 'Platnost tohoto kódu skončila {date}.',
  renew: 'Licence vypršela. Požádej administrátora o nový kód.',
  badge: 'Licence',
  days: '{n} dní, do {date}',
  life: 'Doživotní',
  change: 'Změnit kód',
  close: 'Zavřít',
  noCrypto: 'Tento prohlížeč nemůže kód ověřit. Otevři program v aktuálním Chrome, Edge, Firefox nebo Safari.',
  activated: 'Program je aktivován.',
  allSub: 'Všechny programy v jednom',
  allLibs: 'Všechny',
};

const sk: Texts = {
  title: 'Aktivovať program',
  intro: 'Zadaj aktivačný kód, ktorý si dostal od administrátora.',
  placeholder: 'Aktivačný kód',
  activate: 'Aktivovať',
  invalid: 'Kód nie je platný.',
  wrongProgram: 'Tento kód je pre iný program.',
  expired: 'Platnosť tohto kódu skončila {date}.',
  renew: 'Licencia vypršala. Požiadaj administrátora o nový kód.',
  badge: 'Licencia',
  days: '{n} dní, do {date}',
  life: 'Doživotná',
  change: 'Zmeniť kód',
  close: 'Zavrieť',
  noCrypto: 'Tento prehliadač nemôže overiť kód. Otvor program v aktuálnom Chrome, Edge, Firefox alebo Safari.',
  activated: 'Program je aktivovaný.',
  allSub: 'Všetky programy v jednom',
  allLibs: 'Všetky',
};

const sl: Texts = {
  title: 'Aktiviraj program',
  intro: 'Vpiši aktivacijsko kodo, ki si jo dobil od skrbnika.',
  placeholder: 'Aktivacijska koda',
  activate: 'Aktiviraj',
  invalid: 'Koda ni veljavna.',
  wrongProgram: 'Ta koda je za drug program.',
  expired: 'Ta koda je potekla {date}.',
  renew: 'Licenca je potekla. Prosi skrbnika za novo kodo.',
  badge: 'Licenca',
  days: '{n} dni, do {date}',
  life: 'Trajna',
  change: 'Spremeni kodo',
  close: 'Zapri',
  noCrypto: 'Ta brskalnik ne more preveriti kode. Odpri program v posodobljenem Chrome, Edge, Firefox ali Safari.',
  activated: 'Program je aktiviran.',
  allSub: 'Vsi programi v enem',
  allLibs: 'Vse',
};

const hr: Texts = {
  title: 'Aktiviraj program',
  intro: 'Upiši aktivacijski kod koji si dobio od administratora.',
  placeholder: 'Aktivacijski kod',
  activate: 'Aktiviraj',
  invalid: 'Kod nije valjan.',
  wrongProgram: 'Ovaj kod je za drugi program.',
  expired: 'Ovaj kod je istekao {date}.',
  renew: 'Licenca je istekla. Zatraži novi kod od administratora.',
  badge: 'Licenca',
  days: '{n} dana, do {date}',
  life: 'Doživotna',
  change: 'Promijeni kod',
  close: 'Zatvori',
  noCrypto: 'Ovaj preglednik ne može provjeriti kod. Otvori program u ažuriranom Chromeu, Edgeu, Firefoxu ili Safariju.',
  activated: 'Program je aktiviran.',
  allSub: 'Svi programi u jednom',
  allLibs: 'Sve',
};

const bs: Texts = { ...hr, intro: 'Upiši aktivacioni kod koji si dobio od administratora.', placeholder: 'Aktivacioni kod', invalid: 'Kod nije važeći.', renew: 'Licenca je istekla. Zatraži novi kod od administratora.', noCrypto: 'Ovaj preglednik ne može provjeriti kod. Otvori program u ažuriranom Chromeu, Edgeu, Firefoxu ili Safariju.' };
const cnr: Texts = { ...bs, noCrypto: 'Ovaj pretraživač ne može provjeriti kod. Otvori program u ažuriranom Chromeu, Edgeu, Firefoxu ili Safariju.' };
const sr: Texts = {
  ...bs,
  intro: 'Upiši aktivacioni kod koji si dobio od administratora.',
  invalid: 'Kod nije važeći.',
  wrongProgram: 'Ovaj kod je za drugi program.',
  renew: 'Licenca je istekla. Zatraži novi kod od administratora.',
  change: 'Promeni kod',
  noCrypto: 'Ovaj pregledač ne može da proveri kod. Otvori program u ažuriranom Chrome, Edge, Firefox ili Safari pregledaču.',
};

const mk: Texts = {
  title: 'Активирај ја програмата',
  intro: 'Внеси го кодот за активирање што го доби од администраторот.',
  placeholder: 'Код за активирање',
  activate: 'Активирај',
  invalid: 'Кодот не е важечки.',
  wrongProgram: 'Овој код е за друга програма.',
  expired: 'Овој код истече на {date}.',
  renew: 'Лиценцата истече. Побарај нов код од администраторот.',
  badge: 'Лиценца',
  days: '{n} дена, до {date}',
  life: 'Доживотна',
  change: 'Промени го кодот',
  close: 'Затвори',
  noCrypto: 'Овој прелистувач не може да го провери кодот. Отвори ја програмата во ажуриран Chrome, Edge, Firefox или Safari.',
  activated: 'Програмата е активирана.',
  allSub: 'Сите програми во една',
  allLibs: 'Сите',
};

const bg: Texts = {
  title: 'Активиране на програмата',
  intro: 'Въведете кода за активиране, получен от администратора.',
  placeholder: 'Код за активиране',
  activate: 'Активирай',
  invalid: 'Кодът не е валиден.',
  wrongProgram: 'Този код е за друга програма.',
  expired: 'Този код е изтекъл на {date}.',
  renew: 'Лицензът е изтекъл. Поискайте нов код от администратора.',
  badge: 'Лиценз',
  days: '{n} дни, до {date}',
  life: 'Безсрочен',
  change: 'Смяна на кода',
  close: 'Затвори',
  noCrypto: 'Този браузър не може да провери кода. Отворете програмата в актуален Chrome, Edge, Firefox или Safari.',
  activated: 'Програмата е активирана.',
  allSub: 'Всички програми в една',
  allLibs: 'Всички',
};

const el: Texts = {
  title: 'Ενεργοποίηση προγράμματος',
  intro: 'Εισάγετε τον κωδικό ενεργοποίησης που λάβατε από τον διαχειριστή.',
  placeholder: 'Κωδικός ενεργοποίησης',
  activate: 'Ενεργοποίηση',
  invalid: 'Ο κωδικός δεν είναι έγκυρος.',
  wrongProgram: 'Αυτός ο κωδικός είναι για άλλο πρόγραμμα.',
  expired: 'Αυτός ο κωδικός έληξε στις {date}.',
  renew: 'Η άδεια έχει λήξει. Ζητήστε νέο κωδικό από τον διαχειριστή.',
  badge: 'Άδεια',
  days: '{n} ημέρες, έως {date}',
  life: 'Εφ’ όρου ζωής',
  change: 'Αλλαγή κωδικού',
  close: 'Κλείσιμο',
  noCrypto: 'Αυτό το πρόγραμμα περιήγησης δεν μπορεί να ελέγξει τον κωδικό. Ανοίξτε το πρόγραμμα σε ενημερωμένο Chrome, Edge, Firefox ή Safari.',
  activated: 'Το πρόγραμμα ενεργοποιήθηκε.',
  allSub: 'Όλα τα προγράμματα σε ένα',
  allLibs: 'Όλες',
};

const hu: Texts = {
  title: 'A program aktiválása',
  intro: 'Írd be az adminisztrátortól kapott aktiváló kódot.',
  placeholder: 'Aktiváló kód',
  activate: 'Aktiválás',
  invalid: 'A kód érvénytelen.',
  wrongProgram: 'Ez a kód egy másik programhoz tartozik.',
  expired: 'Ez a kód lejárt: {date}.',
  renew: 'A licenc lejárt. Kérj új kódot az adminisztrátortól.',
  badge: 'Licenc',
  days: '{n} nap, eddig: {date}',
  life: 'Örökös',
  change: 'Kód módosítása',
  close: 'Bezárás',
  noCrypto: 'Ez a böngésző nem tudja ellenőrizni a kódot. Nyisd meg a programot friss Chrome, Edge, Firefox vagy Safari böngészőben.',
  activated: 'A program aktiválva.',
  allSub: 'Minden program egyben',
  allLibs: 'Mind',
};

const ro: Texts = {
  title: 'Activează programul',
  intro: 'Introdu codul de activare primit de la administrator.',
  placeholder: 'Cod de activare',
  activate: 'Activează',
  invalid: 'Codul nu este valid.',
  wrongProgram: 'Acest cod este pentru alt program.',
  expired: 'Acest cod a expirat la {date}.',
  renew: 'Licența a expirat. Cere un cod nou de la administrator.',
  badge: 'Licență',
  days: '{n} zile, până la {date}',
  life: 'Pe viață',
  change: 'Schimbă codul',
  close: 'Închide',
  noCrypto: 'Acest browser nu poate verifica codul. Deschide programul într-un Chrome, Edge, Firefox sau Safari actualizat.',
  activated: 'Programul este activat.',
  allSub: 'Toate programele într-unul',
  allLibs: 'Toate',
};

const ga: Texts = {
  title: 'Gníomhachtaigh an clár',
  intro: 'Cuir isteach an cód gníomhachtaithe a fuair tú ón riarthóir.',
  placeholder: 'Cód gníomhachtaithe',
  activate: 'Gníomhachtaigh',
  invalid: 'Níl an cód bailí.',
  wrongProgram: 'Is do chlár eile an cód seo.',
  expired: 'Chuaigh an cód seo in éag ar {date}.',
  renew: 'Tá an ceadúnas imithe in éag. Iarr cód nua ar an riarthóir.',
  badge: 'Ceadúnas',
  days: '{n} lá, go dtí {date}',
  life: 'Saolré',
  change: 'Athraigh an cód',
  close: 'Dún',
  noCrypto: 'Ní féidir leis an mbrabhsálaí seo an cód a sheiceáil. Oscail an clár i Chrome, Edge, Firefox nó Safari nuashonraithe.',
  activated: 'Tá an clár gníomhachtaithe.',
  allSub: 'Na cláir go léir in aon cheann',
  allLibs: 'Gach ceann',
};

const mt: Texts = {
  title: 'Attiva l-programm',
  intro: 'Daħħal il-kodiċi tal-attivazzjoni li ħadt mingħand l-amministratur.',
  placeholder: 'Kodiċi tal-attivazzjoni',
  activate: 'Attiva',
  invalid: 'Il-kodiċi mhux validu.',
  wrongProgram: 'Dan il-kodiċi huwa għal programm ieħor.',
  expired: 'Dan il-kodiċi skada fil-{date}.',
  renew: 'Il-liċenzja skadiet. Itlob kodiċi ġdid lill-amministratur.',
  badge: 'Liċenzja',
  days: '{n} jiem, sal-{date}',
  life: 'Għal dejjem',
  change: 'Ibdel il-kodiċi',
  close: 'Agħlaq',
  noCrypto: 'Dan il-browser ma jistax jiċċekkja l-kodiċi. Iftaħ il-programm f’Chrome, Edge, Firefox jew Safari aġġornat.',
  activated: 'Il-programm huwa attivat.',
  allSub: 'Il-programmi kollha f’wieħed',
  allLibs: 'Kollha',
};

const tr: Texts = {
  title: 'Programı etkinleştir',
  intro: 'Yöneticiden aldığın etkinleştirme kodunu gir.',
  placeholder: 'Etkinleştirme kodu',
  activate: 'Etkinleştir',
  invalid: 'Kod geçerli değil.',
  wrongProgram: 'Bu kod başka bir program için.',
  expired: 'Bu kodun süresi {date} tarihinde doldu.',
  renew: 'Lisansın süresi doldu. Yöneticiden yeni bir kod iste.',
  badge: 'Lisans',
  days: '{n} gün, {date} tarihine kadar',
  life: 'Ömür boyu',
  change: 'Kodu değiştir',
  close: 'Kapat',
  noCrypto: 'Bu tarayıcı kodu kontrol edemiyor. Programı güncel Chrome, Edge, Firefox veya Safari ile aç.',
  activated: 'Program etkinleştirildi.',
  allSub: 'Tüm programlar tek yerde',
  allLibs: 'Tümü',
};

const srCyrl = Object.fromEntries(Object.entries(sr).map(([k, v]) => [k, toCyrillic(v)])) as Texts;

export const LICENSE_TEXTS: Record<Lang, Texts> = {
  sq, en, it, de, bg, cs, da, el, es, et, fi, fr, ga, hr, hu, lt, lv, mt, nl, pl, pt, ro, sk, sl, sv, bs, cnr, mk, sr, 'sr-Cyrl': srCyrl, tr,
};

export function lic(key: LicenseKey, vars: Record<string, string | number> = {}): string {
  const s = LICENSE_TEXTS[getLang()]?.[key] ?? en[key];
  return s.replace(/\{(\w+)\}/g, (m, k: string) => (k in vars ? String(vars[k]) : m));
}

export { KEYS as LICENSE_KEYS };
